version: '3.0'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fitz
      - POSTGRES_PASSWORD=fitz
